config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    member do
      post :start
      post :stop
    end
  end

  root 'welcome#index'
end

app/models/room.rb
class Room < ActiveRecord::Base
  validates :token, presence: true, uniqueness: true
  validates :timer, presence: true, format: {with: /\A\d+:\d+\z/}

  before_validation :fill_token

  def attrs
    self.attributes.merge(
      timer_sec: timer_sec,
      countdown_sec: countdown_sec
    )
  end

  def timer_sec
    if timer
      m, s = timer.split(':', 2).map(&:to_i)
      m * 60 + s
    end
  end

  def countdown_sec
    if started_at
      timer_sec - (Time.now - started_at).to_i
    end
  end

  def start!
    self.started_at = Time.now
    self.save!
  rescue => e
    self.started_at = nil
    raise e
  end

  def stop!
    self.started_at = nil
    self.save!
  end

  def to_param
    token
  end

  private

  def fill_token
    self.token ||= SecureRandom.hex
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i(show update start stop)

  def show
    respond_to do |format|
      format.html
      format.json { render json: @room.attrs }
    end
  end

  def create
    room = Room.new(timer: params[:timer])
    if room.save
      redirect_to room_path(room.token), notice: 'Create room successfully.'
    else
      redirect_to :root, notice: 'Create room failed.'
    end
  end

  def update
    if @room.update_attributes(timer: params[:timer])
      redirect_to room_path(@room), notice: 'Update room successfully.'
    else
      redirect_to room_path(@room), notice: 'Update room failed.'
    end
  end

  def start
    @room.start!
    redirect_to room_path(@room)
  end

  def stop
    @room.stop!
    redirect_to room_path(@room)
  end

  private

  def set_room
    @room = Room.find_by!(token: params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # render welcome page
  end

  def show
  end

  def new
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PomodoroTimer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container-fluid" role="main">
    <%= yield %>
  </div>

</body>
</html>

app/views/rooms/show.html.erb
<div class="row">
  <div class="col-sm-3 col-md-2 sidebar">
    <ul class="nav nav-sidebar">
      <li><a href="/">home</a></li>
      <li><a class="btn btn-default start-btn">START</a></li>
      <li><a class="btn btn-default stop-btn">STOP</a></li>
    </ul>

    <%= form_for @room do %>
      <div class="form-group">
        <label class="sr-only" for="inputTimer">Timer</label>
        <input type="text" class="form-control" name="timer" id="inputTimer" value="<%= @room.timer %>" placeholder="Enter timer (mm:ss)">
      </div>
      <button class="btn btn-default btn-block" type="submit">update</button>
    <% end %>
  </div>

  <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <div class="jumbotron">
      <h1 class="timer-countdown"><%= @room.timer %></h1>
    </div>
  </div>
</div>

<script>
  var render_countdown = function(sec) {
    var str = Math.floor(sec/60) + ':';
    if (sec % 60 < 10) {
      str += '0' + (sec % 60);
    } else {
      str += (sec % 60);
    }
    $('.timer-countdown').html(str);
  };

  var ajaxSettings = {
    url: '<%= room_path(@room, format: 'json') %>',
    async: true,
    dataType: 'json',
    success: function(data, dataType) {
      if (data.started_at && data.countdown_sec >= 0) {
        timer.countdown = data.countdown_sec;
        start();
      } else {
        stop();
      }
    },
    error: function(data, dataType) {
    }
  };

  var timer = {};

  var countdown = function() {
    render_countdown(timer.countdown);
    if (timer.countdown == 0) {
      stop();
      alert('done');
    }
    if (timer.countdown < 0) {
      stop();
    }
    timer.countdown -= 1;
  }

  var start = function() {
    stop();
    countdown();
    timer.interval = setInterval(countdown, 1000);
  };

  var stop = function() {
    if (timer.interval) {
      clearInterval(timer.interval);
    }
  }

  var sync = function() {
    $.ajax(ajaxSettings);
  };

  $(document).ready(function() {
    sync();
    setInterval(sync, 10 * 1000);

    $('.start-btn').on('click', function() {
      $.post('<%= start_room_path(@room) %>', {}, function() {
        location.reload();
      });
    });

    $('.stop-btn').on('click', function() {
      $.post('<%= stop_room_path(@room) %>', {}, function() {
        location.reload();
      });
    });
  });
</script>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_tag :rooms, {'class' => 'form-signin'} do %>
      <h2 class="form-signin-heading">Please create new room</h2>
      <label for="inputTimer">Timer (e.g. 25:00)</label>
      <input type="text" name="timer" id="inputTimer" class="form-control" value="25:00" placeholder="" required="" autofocus="">
      <button class="btn btn-lg btn-primary btn-block" type="submit">Create new room</button>
    <% end %>
  </div>
</div>